### ISSUE TITLE
The answer to question #6 of chapter 13 seems wrong.

### ISSUE THREAD

**Issue by danli349** [danhalligan/ISLRv2-solutions#14]
Hello: 

I think the answer to question #6 (c,d) of chapter 13 (https://danhalligan.github.io/ISLRv2-solutions/multiple-testing.html) is wrong.
The FDP is defined with V/(V+S), which is (false positive)/(false positive+true positive),
For Bonferroni procedure the false discovery rate will be 0/7, 0/7, 0/3.
For Holm procedure the false discovery rate will be 0/7, 0/8, 0/8.
![image](https://github.com/user-attachments/assets/6c76da61-7ea0-4243-a415-a5575e4c9712)

![image](https://github.com/user-attachments/assets/53a9b367-3239-4f37-904c-6a6558e9b364)

**Comment by danhalligan** [comment]
Agreed -- this looks like an error thanks. Do you want to make a pull request and I'll merge in? If not, I can make the edits.

**Comment by danli349** [comment]
@danhalligan you can make the edits, thanks
