### ISSUE TITLE
Errors in Chapter 13 Question 1

### ISSUE THREAD

**Issue by KalasLavas** [danhalligan/ISLRv2-solutions#2]
I believe there are some errors in the solution of this problem:

b. From definition of FWER
> The family-wise error rate (FWER) generalizes this notion to the setting of m null hypotheses, H01, . . . , H0m, and is defined as the probability of making _**at least one**_ Type I error.

I believe answer should be $1-(1-\alpha)^m$ and $ma$ should be answer of (a)

![image](https://github.com/danhalligan/ISLRv2-solutions/assets/64844410/170626b7-e35b-4f71-9367-dd9b1c8aae53)

d. In solution it is stated that
> we will always have 1 false positive (type 1 error)

This is not true, for example let first p-value be 0.2 then second p-value will be 0.8, since both are larger than 0.05 neither is rejected

I hope I am not mistaken, thank you

**Comment by danhalligan** [comment]
Very good points and thanks for helping! I've updated the answers. Feel free to reopen if you still think there's any mistakes...
